### ISSUE TITLE
Help Page

### ISSUE THREAD

**Issue by elisacoutant** [umts/golf-cart-rentals#388]
Create a help page explaining how to fill out forms and/or restrictions

**Comment by Cobchise** [comment]
I have a list of minor issues like this that I pointed out in the presentation and I still need to put them in issues, I'll do that tomorrow. The reason I haven't yet is I want to get the APP functional first before dealing with smaller issues which would require getting the current PRs merged.

The reason I'm saying this is, if I'm understanding right you're talking about the forms on the app such as rental/create etc,  I don't believe a help page would be a good approach to this problem as there are many different forms each with different requirements/restrictions and thus there would need to be many different help pages, amongst other reasons. A better solution I think would be to edit the CSS so that 'require=true' form fields show to the user with an asterix or some other kind of indicator that this is indeed a required field. Furthermore we should add 'help-text' (which is included in bootstrap and rails I believe) to each field and thus solve the 'unknown restrictions' problem too by indicating for example 'this is the amount, it must be >= 0'.

**Comment by elisacoutant** [comment]
I created this issue because Metin mentioned to me he wanted the forms to be explained (similar to what there is for Flex). I agree with you it might not be the best solution to have it explained on the 'help' page, so we should talk to Metin about this.

**Comment by Cobchise** [comment]
Understood, let's talk to Metin

**Comment by Cobchise** [comment]
Talked to Metin today, he says he wants instructions with screenshots etc on how to complete any forms on our app like rentals, incidents etc. I said I think an asterix by required fields and helper text would be sufficient for this purpose as our app is not as heavy as flex and our forms are fairly straightforward, however he still wants both so let's talk about this and see if we can figure something out.

**Comment by nawilliams** [comment]
fixed in #399
